name: Build CI

on:
  pull_request:
    branches: [ main ]

# For maximum cache coherency, ensure only one outstanding build at any given time
concurrency: release

jobs:
  build:
    # Forks don't need to run the scheduled cron
    if: ${{ github.repository_owner == 'deephaven' || github.event_name != 'schedule' }}

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bake server and server-slim
        uses: docker/bake-action@v2.3.0
        with:
          targets: server,server-slim
          files: server.hcl,server-slim.hcl
          pull: true
        env:
          REPO_PREFIX: ghcr.io/${{ github.repository_owner }}/
          RELEASE: ${{ github.event_name != 'pull_request' }}

      - name: Bake
        uses: docker/bake-action@v2.3.0
        with:
          targets: server,server-slim
          files: server.hcl,server-slim.hcl
          pull: true
        env:
          RELEASE: ${{ github.event_name != 'pull_request' }}
          REPO_PREFIX: ghcr.io/${{ github.repository_owner }}/
