name: Release CI

on:
  pull_request:
    branches: [main]
  push:
    branches: ["main", "release/v*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04-4-16
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bake
        uses: docker/bake-action@v6.2.0
        with:
          targets: server,server-slim,server-all-ai,server-nltk,server-pytorch,server-sklearn,server-tensorflow
          files: server.hcl,server-slim.hcl
          pull: true
        env:
          MULTI_ARCH: true
          RELEASE: ${{ startsWith(github.ref, 'refs/heads/release/v') }}
          REPO_PREFIX: ghcr.io/${{ github.repository_owner }}/
